version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - todo-net

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - todo-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - todo-net

volumes:
  mysql-data:

networks:
  todo-net:
    driver: bridge
