services:
  client:
    build: ./client
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - todo-net

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
    - db
    command: ["sh", "wait-for.sh", "db", "npm", "start"]
    networks:
      - todo-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - todo-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql-data:

networks:
  todo-net:
    driver: bridge
